CREATE TABLE topics (
    id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL UNIQUE,
    message VARCHAR(255) NOT NULL UNIQUE,
    course VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

